### ISSUE TITLE
Installation instructions do not match

### ISSUE THREAD

**Issue by jover** [digipolisgent/robo-drupal-console#4]
**Does not match:**
`"require-dev": { "digipolisgent/robo-drupal-console": "~0.1" }`
AND
`composer require digipolisgent/robo-drupal-console:~0.1`

**Besides that, version ~0.1 doesn't work:**
Your requirements could not be resolved to an installable set of packages.
Problem 1
    - The requested package digipolisgent/robo-drupal-console ~0.1 exists as digipolisgent/robo-drupal-console[dev-develop, dev-feature/base, dev-master] but these are rejected by your constraint.

**Comment by jover** [comment]
So I guess it should be `composer require --dev digipolisgent/robo-drupal-console:dev-master` instead?

**Comment by daften** [comment]
Hi,

Thanks for reporting this, the command was indeed incorrect. Should be fixed in #5 
The reason it fails on the version is because we haven't tagged a version yet. We're finishing up the codeclimate integration to have decent testing and code coverage reports as well, for now, dev-develop is the version to use. We should be tagging later this week (normally tomorrow)!

**Comment by daften** [comment]
@jover I've released an alpha version, you'll need to set your minimum stability to alpha or dev (see https://getcomposer.org/doc/04-schema.md#minimum-stability) in your composer.json for now.
